#!/usr/bin/env php
<?php
require __DIR__ . '/vendor/autoload.php';


use Core\CommandLine\CreateController;
use Core\CommandLine\GreetCommand;
use Symfony\Component\Console\Application;


try {

    $application = new Application();
    $application->add(new GreetCommand());
    $application->add(new CreateController());
    $application->run();
} catch (Exception $e) {

    echo $e->getMessage();
}